import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hedgemyfunds community chapter",
  description: "Generated by create next appJoin the Community Chapter: Empowering College Students to Connect, Learn, and Grow in the World of Finance.",
  

};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
